FROM python:3.11-slim

# Criar diretório da aplicação
WORKDIR /app

# Instalar dependências do sistema
RUN apt-get update && apt-get install -y gcc libmariadb-dev && rm -rf /var/lib/apt/lists/*

# Copiar requirements
COPY requirements.txt .

# Instalar dependências do Python
RUN pip install --no-cache-dir -r requirements.txt

# Copiar código da aplicação
COPY . .

# Expor porta da API
EXPOSE 8000

# Rodar a aplicação
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--reload"]
